version: '3'
networks:
  scalable-go:

services:

  rabbitmq:
    container_name: ${RABBITMQ_SERVICE_NAME}
    hostname: ${RABBITMQ_SERVICE_NAME}
    image: ${RABBITMQ_DOCKER_VERSION}
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_AMQP_PORT}:5672     # AMQP port. Rich messaging for server.
      - ${RABBITMQ_MANAGEMENT_PORT}:15672                    # Management port, if plugin is enabled.
    networks: 
      - scalable-go

  entryserver:
    container_name: ${ENTRYSERVER_SERVICE_NAME}
    hostname: ${ENTRYSERVER_SERVICE_NAME}
    image: ${ENTRYSERVER_DOCKER_VERSION}
    environment:
      - ENTRYSERVER_PORT=${ENTRYSERVER_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVICE_NAME=${RABBITMQ_SERVICE_NAME}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
    ports:
      - ${ENTRYSERVER_PORT}:${ENTRYSERVER_PORT}
    networks:
      - scalable-go
    depends_on:
      - ${RABBITMQ_SERVICE_NAME}